# Configuracion de la aplicacion
spring.application.name=wallet-manager

# Configuracion de la base de datos
# spring.datasource.url=jdbc:postgresql://localhost:5432/wallet
# spring.datasource.username=postgres
# spring.datasource.password=postgres
# spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Configuracion de JPA y Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Configuracion de documentacion Swagger
springdoc.swagger-ui.path=/docs

# Configuracion de Logging
logging.level.org.springframework.web=DEBUG
